CREATE TABLE IF NOT EXISTS "proxy_variables" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar(255) NOT NULL,
	"type" varchar(50) NOT NULL,
	"formula" text NOT NULL,
	CONSTRAINT "proxy_variables_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "allmoxy_products" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar(255) NOT NULL,
	"status" varchar(50),
	"pricing_proxy_id" integer,
	"export_proxy_id" integer,
	CONSTRAINT "allmoxy_products_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "attribute_grids" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar(255) NOT NULL,
	"columns" jsonb NOT NULL,
	"key_column" varchar(255) NOT NULL,
	CONSTRAINT "attribute_grids_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "attribute_grid_rows" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"grid_id" integer NOT NULL,
	"lookup_key" varchar(255) NOT NULL,
	"row_data" jsonb NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "allmoxy_products" ADD CONSTRAINT "allmoxy_products_pricing_proxy_id_proxy_variables_id_fk" FOREIGN KEY ("pricing_proxy_id") REFERENCES "public"."proxy_variables"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "allmoxy_products" ADD CONSTRAINT "allmoxy_products_export_proxy_id_proxy_variables_id_fk" FOREIGN KEY ("export_proxy_id") REFERENCES "public"."proxy_variables"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "attribute_grid_rows" ADD CONSTRAINT "attribute_grid_rows_grid_id_attribute_grids_id_fk" FOREIGN KEY ("grid_id") REFERENCES "public"."attribute_grids"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
